Creation of GDS 2.0 Sandbox and Browser Guide
neo4j-graph-examples/airport-routes pull request #1
Opened 2022-02-24 19:09 UTC by cj2001

This PR is to create the new GDS 2.0 browser guide.  It is presently in this Sandbox-structured repository since it will eventually be used to create the GDS 2.0 Sandbox itself.  So the review I am asking for presently is specifically on the browser guide content.

The dataset has been changed away from the Game of Thrones graph to the [airline routes graph](https://github.com/krlawrence/graph) used in the [Kelvin Lawrence's Gremlin book](http://kelvinlawrence.net/book/PracticalGremlin.html).  This graph was chosen, based on the requirements suggested by @moxious, because:

1. It is use-case agnostic (i.e. it is understandable by a large group of people).
2. It has an obvious data model that doesn't require too much time to teach.
3. It is timeless and general.
4. It is small, meaning there are not worries about scalability (which would be a more advanced subject).
5. It is general enough that it can be used for a few different types of demonstrations.

Note that this has been tested with `neo4j-graph-data-science-2.0.0-alpha03.jar` (it will not work with GDS 1.x for obvious reasons).  However, there are not Sandboxes running with that version of GDS yet, so you will need to try this out locally.  In order to run the browser guide without the Sandbox, use the following:

```
:play https://guides.neo4j.com/graph-data-science2/gds_browser_guide2.html
```

Once there is a Sandbox to test this on, I expect that there will be the need for an additional PR to get the Sandbox itself up and functional.

**For review:**
/cc @moxious, @jexp, @zach-blumenfeld, @pdathar, @breakanalysis

**For visibility/feedback:**
/cc @jcneo4j, @aliciaframe, @laeg

2022-02-28 13:28 UTC, moxious requested changes

2022-02-28 13:28 UTC, moxious commented on README.adoc
> +Import flat files (csv, json, etc) using Cypher's https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], https://neo4j.com/labs/apoc/[APOC library], or https://neo4j.com/develope
links: whenever referring to Neo4j's domain, just add ?ref=gds-sandbox on the end for internal tracking.

Instead of `https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/`, use `https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/?ref=gds-sandbox` instead (single query parameter)

2022-02-28 13:28 UTC, moxious commented on README.adoc
> +Download the zip file link:{repo}/raw/master/{name}.zip[{name}.zip] and add it as "project from file" to https://neo4j.com/developer/neo4j-desktop[Neo4j Desktop^].
link ref

2022-02-28 13:28 UTC, moxious commented on README.adoc
> +:long-name: Graph Data Science 2
you might consider removing "2" and "2.0" because months from now the minor and patch versions will move on but this is likely to live longer.  (I.e. avoid later questions "does the 2.0 sandbox work with 2.1.5?") Most new people coming to this resource won't know anything previous ever existed.  They just arrived, everything is new to them.

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> += Graph Algorithms
note because I can't comment on the other file directly as it's added -- this adoc is where it's at, it looks like the rendered browser guide is also getting committed to this repo.  Double check - the rendered guide might not should be included because it's a big file, hard to read directly, and rendered by the toolchain in the repo.  Michael might know.

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +Traditional data science and machine learning applications has relied on creating knowledge and understanding using columnar data.  Each row of data (or each data point) is treated as independent fro
Don't include a link to an outside resource on the very first slide of the browser guide. They just arrived, want to keep them here for just a second.  If the resource is useful, put it at the end in related links or somesuch.

Add a graphic to the plain text found on the very first slide.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/5471710/155989647-6a0fe0e0-7401-447d-8fcd-b29ea2380831.png">

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +The Neo4j Graph Data Science (GDS) library contains a set of graph algorithms, exposed through Cypher procedures.  Graph algorithms provide insights into the graph structure and elements, for example
silly question but is it a library or just GDS?   On the main product page the word "library" isn't there.   Maybe just refer to it as GDS rather than "The GDS Library"

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +* How to create a graph projection (also referred to as an "in-memory graph")
Rephrase to focus on short verb phrases (easier to read, punchier)
* Create a graph projection
* Run a graph algorithm on a projection
* Show & interpret example results

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +The official GDS library documentation can be found link:https://neo4j.com/docs/graph-data-science/current/[here^].
link ref

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +The Neo4j Graph Data Science (GDS) library contains a set of graph algorithms, exposed through Cypher procedures.  Graph algorithms provide insights into the graph structure and elements, for example
Also -- consider removing the bit about maturity.  Beginning users don't know what you mean or care on this point, I suspect.   Browser has content limitations before scroll, ideally the content would get just short enough so the single slide doesn't need to scroll.

<img width="937" alt="image" src="https://user-images.githubusercontent.com/5471710/155990139-19371843-ed6e-4a5c-b599-5bf95eb85b97.png">

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +== Loading the data
Question: do we need this slide at all?  Just wondering out loud.  The idea with the sandbox would be the data is already pre-populated.  We know loading & cypher is complicated for users, and going into this is delaying getting into "the good parts" (GDS)

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +The first step in executing any GDS algorithm is to create a graph projection (also referred to as an in-memory graph) under a user-defined name.  Graph projections are subsets of our full graph to b
really minor but whenever you can add a picture to give some visual illustration to particularly abstract ideas like this, it helps (if we have one)

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +== Algorithm syntax: available execution modes
Just my $0.02 but this could be left to later or omitted in a beginner experience. They haven't run an algorithm yet, so this kind of information might not make sense (yet).

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +PageRank can be run on a basic graph, such as what we are using here, or with a weighted graph.  To see how to run it on a weighted graph, please explore the link:https://neo4j.com/docs/graph-data-sc
not sure we should redirect them to the docs before we get to a native sandbox example.  This is a good slide with good information - but consider putting it after "native in-sandbox" examples like pagerank on the next slide.

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +== Cleaning up
See above comment about dropping in-memory graphs....that earlier material can be removed because you cover it here in any case.

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +If you would like to work efficiently with larger graphs using a fully-managed cloud service, then check out link:https://neo4j.com/cloud/aurads[AuraDS^]!
here we had discussed two next steps.   On AuraDS, it's worth mentioning this will require a credit card and is not a free option.  Secondarily, there is the "self-nurture" path.  What if AuraDS isn't a fit for me (yet)?  Secondary path would be (docker / desktop / etc)

2022-02-28 13:28 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +Congratulations!  You have taken your first steps into using the Neo4j Graph Data Science (GDS) library!  This tutorial just looked at the basics of how to run graph algorithms and demonstrated the a
link ref

2022-02-28 14:14 UTC, AliciaFrame commented on documentation/gds_browser_guide2.adoc
> +The Neo4j Graph Data Science (GDS) library contains a set of graph algorithms, exposed through Cypher procedures.  Graph algorithms provide insights into the graph structure and elements, for example
> silly question but is it a library or just GDS? On the main product page the word "library" isn't there. Maybe just refer to it as GDS rather than "The GDS Library"

From a marketing perspective, we're moving towards dropping the "library" and positioning Neo4j as a "graph data science platform" - so I would drop library here. "Neo4j Graph Data Science incorporates our graph database, graph algorithms and machine learning procedures, and visualization tools like bloom"

2022-03-05 01:58 UTC, zach-blumenfeld requested changes
Lots of things :) .  Please see inline comments.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +Traditional data science and machine learning applications has relied on creating knowledge and understanding using columnar data.  Each row of data (or each data point) is treated as independent fro
Some minor grammer things in here.  WIll this guide get a quick edit?

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +image::https://guides.neo4j.com/graph-data-science2/air_route_schema.png[float="right",width=300]
The schema image renders quite small for me in browser. Minor detail but if it could be made bigger that would be great.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Loading the data
I actually like this idea as long as it works.  As we have seen even on internal slack chats, loading is where a lot of users can get tripped up and data scientists often start with csvs. 

A couple things to validate:
1. Make sure it is "idempotent" if possible - If a user runs this twice by accident it shouldn't change the data from the first run.
2. From an organizational standpoint, we should host this data on a neo4j owned url rather than a personal github repo.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +    'https://raw.githubusercontent.com/cj2001/bite_sized_data_science/main/data/airport-node-list.csv'
I am not sure this is best practices for performant load csv.   You would want to merge nodes then match->merge relationships, but I suppose if you intend to keep the source data in a first normal form it is a very minor point.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Graph creation
I would title this as "Graph Projection" instead of "Graph Creation" to make it clear

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +Native projections provide the fastest performance for creating an graph projection.  They take 3 mandatory arguments: `graphName`, 'nodeProjection', and 'relationshipProjection'.  There are also opt
make sure you use back-ticks instead of single quotes for the arguments. 

on a pedantic note  - technically these are parameters, not arguments. Function parameters are the names listed in the function's definition. Function arguments are the real values passed to the function.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Graph catalog: creating a graph with native projections
again I would try to replace the verb 'create' with 'project'

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +----
this shouldn't be a runnable/playable code block in the guide....it is runnable for me for some reason and obviously just makes an error

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +By using Cypher projections, we can specify many things, such as requirements on the node and relationship properties and more sophisticated relationships.  To see more examples of creating Cypher gr
If you cover cypher projections specifically, it would be best to reference a use case where the flexibility/sophistication is actually needed. A common example is the weighted single-mode projection on small subset of the graph.  Otherwise it is sort of like "what's the point"? and it may lead to new users selecting cypher projections over native projections where they shouldn't be just because they are comfortable with cypher syntax. (I feel like it is better that novice don't know about cypher projections until they really understand them and and/or need them).

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +There are times where native projections are not expressive enough to capture exactly what you need in the graph.  In these cases, Cypher can be used to create the graph projection.  The overall synt
Is it possible to more explicitly reference the performance trade-off so novice users understand?

Maybe something like this? 
>There are times where native projections are not expressive enough to capture exactly what you need in the graph.  In these cases, Cypher can be used to create the graph projection. Instead of optimizing for scale and performance like the native projection, Cypher projections are specifically optimized for flexibility and customizability to support developmental analysis and experimentation on smaller subsets of the graph.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.list('graph-name')
would you want the 'graph-name' to be in the catalog though before the user runs it? or is that not the intent of the guide to show a working example that way?

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.drop('graph-name')
same question here.  It feels like the browser guide is telling me to run this drop command....but then I get an error.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Interpretting results of an algorithm
The `gds.util.asNode` seems a bit low level to have it's own page.  As a novice user, it is not clear where this applies relative to the different algorithms and execution modes.  Probably better to introduce in action when you use a stream method in another example...then it will only take a quick 1-2 sentences to explanation there if you like.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.project(
Playing this in sequence results in an error as we already projected a graph with the same name in a previous step.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +ORDER BY score DESC, iata ASC
maybe 
```
CALL gds.pageRank.stream('routes')
YIELD nodeId, score
RETURN gds.util.asNode(nodeId).iata AS iataCode, gds.util.asNode(nodeId).descr AS description, score
ORDER BY score DESC,  iataCode ASC
```

for dumb-dumbs like me that do not have airports memorized  by IATA codes...or know what IATA codes are.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +MATCH (a:Airport)
Same advice here, to include the description for context:
```
MATCH (a:Airport)
RETURN a.iata,a.descr, a.pagerank
ORDER BY a.pagerank DESC, a.iata ASC
```

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.project(
Again, this results in an error when running the browser guide in sequence since we didn't drop the previous graph.  I will make this my last comment on this type of thing to avoid being repetitive...I suppose if this is important we just need to run through and make sure the right commands are included/excluded.

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +As with centrality measurements, there are many ways to identify communities within a graph.  We will cover the popular Louvain Modularity method in this section.  This algorithm finds clusters withi
but why should I care about this though? :) ...Is it possible to connect this to the data/use case to  provide motivation. i.e. "PageRank and other centrality metrics can help us understand the the most popular/central/influential airports.  But what if we are interested in analyzing how airport routes correlate across the whole graph? and if certain groups of airports have particularly high travel rates between them forming natural clusters across the globe?  This is where community detection comes in...."

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +As with the previous algorithm categories of centrality and community detection, there are a variety of ways to calculate node similarity.  In general, node similarity is computed between pairs of no
There are <s>a variety of</s> various ways to calculate node similarity

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +As with the previous algorithm categories of centrality and community detection, there are a variety of ways to calculate node similarity.  In general, node similarity is computed between pairs of no
As with community detection would be great to add motivation here

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +To implement this, GDS starts by considering all source nodes in the graph that have an outgoing relationship.  So suppose there is a relationship between node `n` and node `m`.  For each `(n, m)` pa
the implementation paragraph is a bit confusing,

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +Other ways of limiting the number of calculations done include by providing a minimum value of degree for a node to be considered in the overall calculations, such as below where we require a minimum
"Other ways of limiting the number of calculations done include by providing..." - fix sentence

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +        degreeCutoff: 25
is this query supposed to have a similarity cutoff instead of 'degreeCutoff'?

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +
I am still unclear on how to interpret node similarity in the context of this data and why it is important.  Can we add that explanation in the examples?

2022-03-05 01:58 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +Like all of the other algorithm categories we have explored, there are several approaches possible for path finding.  Generally speaking, the purpose of path finding is to find the shortest path betw
as with the past sections, would be great to motivate the use case for path finding within the context of this dataset and why it would be important.

2022-03-05 02:10 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Algorithm syntax: available execution modes
> Just my $0.02 but this could be left to later or omitted in a beginner experience. They haven't run an algorithm yet, so this kind of information might not make sense (yet).

I agree with this feedback for this section and also the graph projection pieces.  

I would also add on to that. While I am not aware of all the context around sandbox objectives, starting with high-level problems like "what airport(s) are most influential" and "how to calculate fastest routes from airport A to B", then digging into the projections, and different algorithm areas would be an interesting applied beginner tutorial.  At current state this seems duplicative with graph academy courses which are focused on reviewing feature-by-feature and which also have challenge problems that connect to a sandbox

2022-03-05 13:23 UTC, laeg commented on documentation/gds_browser_guide2.adoc
> +By using Cypher projections, we can specify many things, such as requirements on the node and relationship properties and more sophisticated relationships.  To see more examples of creating Cypher gr
+1 on leaving cypher projections out for novice users

2022-03-05 13:27 UTC, laeg commented on documentation/gds_browser_guide2.adoc
> +ORDER BY score DESC, iata ASC
I don't know how others feel, but I would personally put a with between the return for readability.

```
CALL gds.pageRank.stream('routes')
YIELD nodeId, score
WITH gds.util.asNode(nodeId) AS aNode
RETURN aNode.iata AS iataCode, aNode.descr AS description, score
ORDER BY score DESC,  iataCode ASC
```

Might also be worth putting a comment

2022-03-07 08:07 UTC, Mats-SX commented
@cj2001 Just wondering, this new Browser Guide, will it take over the name of the Engineering-authored `:play graph-data-science`? We decided to not keep developing ours and would be happy to see this new one take over the same name. That way we don't need to put up any kind of warning signs around the old one telling people to stay away from it.

Cheers!

2022-03-07 14:26 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> += Graph Algorithms
The rendered browser guide appears in the repo for the previous GDS browser guide, so I was just going with that model.

2022-03-07 14:29 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +The first step in executing any GDS algorithm is to create a graph projection (also referred to as an in-memory graph) under a user-defined name.  Graph projections are subsets of our full graph to b
I don't see one in the API docs.  @AliciaFrame do you have something that you use for this?

2022-03-07 14:32 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +== Graph creation
I had considered that, but decided against it because the concept of a "projection" of a graph is not initially intuitive to a beginning user.  I figured the idea of "creation" is more obvious and then we walk them into the space of using the term "projection."

2022-03-07 14:38 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +ORDER BY score DESC, iata ASC
@laeg I definitely agree that the use of `WITH` makes it more readable.  However, the API docs don't use it and I think it might be confusing to add it in here but not there.

2022-03-07 14:42 UTC, cj2001 commented
> @cj2001 Just wondering, this new Browser Guide, will it take over the name of the Engineering-authored `:play graph-data-science`? We decided to not keep developing ours and would be happy to see this new one take over the same name. That way we don't need to put up any kind of warning signs around the old one telling people to stay away from it.
> 
> Cheers!

@Mats-SX es, that is exactly what this is for. So no need to worry about updating the old one. This one will work with GDS 2.x and has a graph (airport routing) that will ideally not go out-of-date like the GoT one. 🎉

2022-03-07 15:17 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +Traditional data science and machine learning applications has relied on creating knowledge and understanding using columnar data.  Each row of data (or each data point) is treated as independent fro
Absolutely!  And you are part of that edit!  😄

2022-03-07 15:30 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +The Neo4j Graph Data Science (GDS) library contains a set of graph algorithms, exposed through Cypher procedures.  Graph algorithms provide insights into the graph structure and elements, for example
@AliciaFrame I have gone through and changed the wording from GDS library to GDS.  It reads funny to me, likely because it is new to me.  So if you can please skim over it and make sure this language looks correct based on the new marketing perspective, that would be great.

2022-03-07 15:50 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +== Loading the data
1. I have brought in the CSV files to this repo, so it is not pointing at the BSN4DS repo anymore.  
2. I do think that it helps to show the ingest of the files and, of course, agree on making this idempotent.  I have confirmed that you can run these ingest queries several times and not change the graph.

So it comes down to whether we want to include this population section or not.  Final votes?

2022-03-07 15:55 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +    'https://raw.githubusercontent.com/cj2001/bite_sized_data_science/main/data/airport-node-list.csv'
The original data is in this big airport node list.  I could separate this into several different relationship files, but I did it this way to minimize the number of times using `LOAD CSV`.  Ultimately the data will be pre-populated in the Sandbox via dump files, so this won't actually be used.  If, based on the previous comment from @moxious, we eliminate this slide, then the point is moot.

@jexp As the Cypher God 😉  could you please let us know where you stand on this?

2022-03-07 15:57 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +== Graph catalog: creating a graph with native projections
Hmm...toying with some wording here.  This gets a lot easier if we remove the Cypher projections (see below).  What are you thoughts on something like "Using native projections to create in-memory graphs?"

2022-03-07 17:49 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +There are times where native projections are not expressive enough to capture exactly what you need in the graph.  In these cases, Cypher can be used to create the graph projection.  The overall synt
I like it!

2022-03-07 18:05 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +By using Cypher projections, we can specify many things, such as requirements on the node and relationship properties and more sophisticated relationships.  To see more examples of creating Cypher gr
OK...I am going to leave it out, particularly because we know that there is more coming with Cypher projections in the not-so-distant future.  We can always choose to add it back in.  But I am going to put a quick sentence in at the end of the native projection session indicating that it is there but beyond the scope of this introduction.

2022-03-07 18:25 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +== Algorithm syntax: available execution modes
In a way they are intended to be a little duplicative.  Some users will never go to Graph Academy just based on the time commitment.  So this gives them a real quick way to plow through without watching the video.  Those who are interested in a more thorough coverage of the topic will go to GA, perhaps in addition to this guide.

2022-03-07 18:29 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +== Interpretting results of an algorithm
I see your point.  Because there is a bit of text to it that would make for too full of a card, I did keep it as its own separate card.

2022-03-07 19:07 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.project(
This is addressed if you look at the card that says "If you need to recreate that graph projection...".  This was done because some people skip many cards to get to the few that they care about.  So this allows them to jump in completely right there.

2022-03-07 19:15 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.project(
See previous comment.

2022-03-07 19:21 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +To implement this, GDS starts by considering all source nodes in the graph that have an outgoing relationship.  So suppose there is a relationship between node `n` and node `m`.  For each `(n, m)` pa
I agree.  I have just tried some new wording.  Please let me know if you think this is more clear.

2022-03-07 19:25 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +
Check out the wording clarification under the node similarity description card and let me know if this clears it up.

2022-03-08 16:02 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +    'https://raw.githubusercontent.com/cj2001/bite_sized_data_science/main/data/airport-node-list.csv'
Also, another comment on the airport node list...

...this is the same file (albeit in a different repo) that is used in the Bite-Sized series.  So if data scientists go back and forth between the BSN4DS series and this browser guide it will be a consistent dataset.

2022-03-08 18:21 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +CALL gds.graph.list('graph-name')
This was meant to be an example and non-playable.  I have removed the play-ability from it so it should make more sense now.

2022-03-08 18:27 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +image::https://guides.neo4j.com/graph-data-science2/air_route_schema.png[float="right",width=300]
I have updated the figure to something created via arrows.app.  Please let me know what you think.

2022-03-08 18:50 UTC, moxious commented on documentation/gds_browser_guide2.adoc
> +== Loading the data
If Zach likes it go ahead and keep it.  His points 1 & 2 are good ones tho

2022-03-11 20:59 UTC, moxious approved these changes

2022-03-12 07:18 UTC, zach-blumenfeld reviewed
Looking better overall.  Just some minor notes  - mostly around node similarity

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Graph catalog: creating a graph with native projections
> Using native projections to create in-memory graphs?


Works.

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +As with centrality measurements, there are many ways to identify communities within a graph.  Community detection is a useful tool for identifying regions of a graph that are densely clustered.  For
The second sentence of this paragraph is a bit confusing.  Maybe clean up.  Something like 

> For example, in our airport routes graph, community detection can help us identify natural clusterings of airports that formed overtime from the high travel rates they have between each other.


or

> For example, in our airport routes graph, community detection can help us find regions of the globe where airports have high travel rates between each other or where airports form natural clusters based on their density within a region.

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +We will cover the popular Louvain Modularity method in this section.  This algorithm finds clusters within a graph by measuring the density of nodes.  This is quantified through the _modularity_, whi
Some minor fixes for this paragraph: 

We will cover the popular Louvain Modularity method in this section. This algorithm finds clusters within a graph by measuring the **relative** density of ~~nodes~~ relationships.  This is quantified through the _modularity **score**_, which is a comparison of the density of ~~connections~~ relationships within a cluster to an average or random sample. ....

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +In this section we will use the common link:https://en.wikipedia.org/wiki/Dijkstra's_algorithm[Dijkstra's algorithm^] to find the shortest path between two nodes.  Unlike the previous examples, we wi
double check the link https://en.wikipedia.org/wiki/Dijkstra's_algorithm. I think you want this right? : https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Algorithm syntax: available execution modes
fair enough

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +== Graph creation
fair enough

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +
Ahh.  I see.  This graph isn't really one where similarity will make sense, we run it here as an example for the syntax and you refer to the recommendation systems use case to speak to why it is important.  


Just my opinion - It may be worth mentioning quickly that while this specific type of graph is not ideal for node similarity, you're going to demonstrate some examples to introduce you to the syntax and usage patterns.

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +As with the previous algorithm categories of centrality and community detection, there are various ways to calculate node similarity.  In general, node similarity is computed between pairs of nodes t
For the last sentence, 

In this section we will use the aptly named https://neo4j.com/docs/graph-data-science/current/algorithms/node-similarity/:[Node Similarity GDS algorithm] leveraging the common approach of  link:https://en.wikipedia.org/wiki/Jaccard_index[Jaccard similarity^] to calculate pairwise similarity.

Or something like that, so we refer to the algo specifically.  Also I think in 2.0 users will have the option to switch Jaccard out with different metrics (i.e. overlap and weighted overlap)

2022-03-12 07:18 UTC, zach-blumenfeld commented on documentation/gds_browser_guide2.adoc
> +Node similarity considers every relationships between every node.  If there is a relationship between nodes `n` and `m`, the algorithm then explores the other relationships individually of these two
I actually think the commented out portion below explains node similarity better than this paragraph.  I know this is a tough one to exaplain in a few sentences.   My best try below:

>Jaccard based node similarity looks at how many common _neighbors_ are shared between a pair of two nodes.  In this context, a node’s _neighbor_ refers to any other node connected by an outbound relationship.  Loosely speaking, the larger the proportion of shared neighbors between the two nodes in the pair, the higher their similarity will be, with a minimum value of 0 (no shared neighbors) and a max value of 1 (all neighbors are shared).

2022-03-16 19:16 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +
In running this on the graph, I see that the nodes that come up as most similar do actually make sense.  For example, Santa Fe comes up as most similar to Flagstaff, Durango, Yuma, which make sense to me.  I am not going to word this too strongly, because I think it would actually cause more confusing than it would clarify.  But I will add a few words to that effect.

2022-03-17 09:23 UTC, zach-blumenfeld approved these changes

2022-03-17 19:21 UTC, cj2001 commented on documentation/gds_browser_guide2.adoc
> +In this section we will use the common link:https://en.wikipedia.org/wiki/Dijkstra's_algorithm[Dijkstra's algorithm^] to find the shortest path between two nodes.  Unlike the previous examples, we wi
They both work from my end...

2022-03-18 20:40 UTC, cj2001 commented
I am merging this now and will create a new branch for any edits between now and launch

2022-03-18 20:40 UTC, merged